### ISSUE TITLE
Connection to elasticsearch is broken from time-to-time

### ISSUE THREAD

**Issue by vohtaski** [koemei/koemei-widget#240]
Error message on video page: when a search term for example "testing" in the video page, and "Global search" is chosen, no result is displayed, but an error message. 

![image](https://cloud.githubusercontent.com/assets/7411518/6057930/d4530aea-ad22-11e4-9728-cc446159b292.png)

log
```
13:09:34,228 INFO  [shared.model.scheduler_api] Task 1608333 scheduled to run
13:12:43,621 INFO  [paste.httpserver.ThreadPool] kill_hung_threads status: 20 threads (0 working, 20 idle, 0 starting) ave time N/A, max time 0.00sec, killed 0 workers
13:20:20,093 WARNI [shared.libs.pyes] Removed server http://ip-172-30-0-190.ec2.internal:9200 from active pool
13:20:20,093 ERROR [shared.libs.pyes] Client error: 3 retries left
Traceback (most recent call last):
  File "/home/tg/www/sites/shared/libs/pyes/connection_http.py", line 99, in execute
    response = conn.urlopen(**kwargs)
  File "/home/tg/www/tgenv/lib/python2.6/site-packages/urllib3-1.5-py2.6.egg/urllib3/connectionpool.py", line 442, in urlopen
    timeout)
TimeoutError: HTTPConnectionPool(host='ip-172-30-0-190.ec2.internal', port=9200): Request timed out. (timeout=30.0)
13:20:20,098 ERROR [shared.utils.elasticsearch_connector] Error searching media for right*
13:20:20,098 ERROR [shared.utils.elasticsearch_connector] list index out of range
13:20:20,099 ERROR [shared.utils.elasticsearch_connector] Traceback (most recent call last):
  File "/home/tg/www/sites/shared/utils/elasticsearch_connector.py", line 221, in search_media
    self.total = results.total
  File "/home/tg/www/sites/shared/libs/pyes/es.py", line 1478, in total
    self._do_search()
  File "/home/tg/www/sites/shared/libs/pyes/es.py", line 1439, in _do_search
    self._results = self._search_raw(self.start, self.chuck_size)
  File "/home/tg/www/sites/shared/libs/pyes/es.py", line 1636, in _search_raw
    doc_types=self.doc_types, **query_params)
  File "/home/tg/www/sites/shared/libs/pyes/es.py", line 1204, in search_raw
    return self._query_call("_search", body, indices, doc_types, **query_params)
  File "/home/tg/www/sites/shared/libs/pyes/es.py", line 428, in _query_call
    return self._send_request('GET', path, query, params=query_params)
  File "/home/tg/www/sites/shared/libs/pyes/es.py", line 395, in _send_request
    response = self.connection.execute(request)
  File "/home/tg/www/sites/shared/libs/pyes/connection_http.py", line 93, in execute
    self._local.server = server = self._get_server()
  File "/home/tg/www/sites/shared/libs/pyes/connection_http.py", line 129, in _get_server
    raise NoServerAvailable(ex)
NoServerAvailable: list index out of range

13:20:50,979 WARNI [urllib3.connectionpool] Retrying (3 attempts remain) after connection broken by 'CannotSendRequest()': /media_transcripts/_search?from=0&size=10
13:20:50,979 INFO  [urllib3.connectionpool] Starting new HTTP connection (5): ip-172-30-0-190.ec2.internal
```

Reason: connection to elastic search is lost

**Comment by vohtaski** [comment]
My wild guess is that the problem is in urllib3 library.
I have version 1.8 on my virtual machine and it always work.
On prod we had version 1.5. I updated now production machine to version 1.8.
Let's hope it works.

Please do test global search. If we don't encounter 'Error searching videos, pls try again" message in the nearest future, then that's was the reason.
If we see this problem again, then I have another possible reason in mind.
